spring:
  datasource:
#    url: jdbc:mysql://159.65.8.170:3306/monument_book
#    username: root
#    password: 1213@A*#
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    url: jdbc:mysql://localhost:3306/monument_book
#    username: root
#    password: 1234!@#$
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/monument_book
    username: root
    password: 1213@A*#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
server:
    port: 8080
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
logging:
  level:
    org.springframework.security: DEBUG